---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: kong-ingress
  
- name: "Apply Kong Ingress Controller"
  become_user: kube
  shell: "kubectl create -f {{ kong_ingress.yml_url }}"
  tags: kong-ingress

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: kong-ingress