---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: nginx-ingress

- name: "Download Deployment YML"
  get_url:
    url: "{{ nginx_ingress_url }}"
    dest: "{{ tmp_dir }}/deploy.yaml"
    mode: 0777
  tags: nginx-ingress

- name: "Change when Metallb is active"  
  shell: "sed -i 's/type: NodePort/type: LoadBalancer/' {{ tmp_dir }}/deploy.yaml"
  when: "additional_features.metallb"
  tags: nginx-ingress
  
- name: "Apply NGINX Ingress Controller"
  become_user: kube
  shell: "kubectl apply -f {{ tmp_dir }}/deploy.yaml"
  tags: nginx-ingress

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: nginx-ingress