---
- hosts: k8s_cluster
  become: yes
  roles:
    - role: user
 
- hosts: k8s_cluster
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - role: container
    - role: kubeadm

- hosts: master
  become: yes
  roles:
    - role: kubernetes/master

- hosts: node
  become: yes
  roles:
    - role: kubernetes/node

- hosts: master
  gather_facts: yes
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: features/helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: features/metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb